openapi: 3.0.3
tags:
  - name: Home Devices Prioritization
    description: Home devices prioritization available for *Network-as-a-Service* API clients
paths:
  /users/{user_id}/devices/this/prioritization:
    put:
      description: |-
        Updates the device prioritization status when there is a device connected to the user home network matching the input criteria provided in request body. Setting prioritization to CS0 removes any previous prioritization. **The device to be prioritized is replaced by the special keyword 'this' in the API resource referring to the device match.**
         - The device to be prioritized is identified by the internal IP address of that device in the home network and the public IP address identifying that home network (external IP address of the home router).
         - In case there is no device matching the input criteria, the operation returns a 404 error.
      tags:
        - Home Devices Prioritization
      operationId: updateDevicePrioritization
      parameters:
        - in: header
          name: x-correlator
          required: false
          description: Correlation id for the different services
          schema:
            type: string
        - $ref: '#/components/parameters/UserId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DevicePrioritizationUpdate'
        required: true
      summary: Set the desired DSCP prioritization status of the device matching the input criteria
      responses:
        '204':
          headers:
            x-correlator:
              description: Correlation id for the different services
              schema:
                type: string
          description: New prioritization passed all validations and was applied
        '400':
          $ref: '#/components/responses/InvalidArgument'
        '401':
          $ref: '#/components/responses/Unauthenticated'
        '403':
          $ref: '#/components/responses/PermissionDenied'
        '404':
          $ref: '#/components/responses/NoDeviceMatch'
        '409':
          $ref: '#/components/responses/PrioritizationConflict'
        '500':
          $ref: '#/components/responses/Internal'
        '503':
          $ref: '#/components/responses/RouterActionsUnavailable'
        '504':
          $ref: '#/components/responses/Timeout'
info:
  title: Home Devices Prioritization API - DRAFT VERSION
  description: |-
    Allows to prioritize user devices connected to the user home network as a NaaS capability.

    # Relevant Definitions and concepts

    - **Home Devices**: user devices connected to the user home network.
    - **NaaS**: *Network-as-a-Service* model where OB Network resources are exposed to third parties through APIs. In this particular API, device prioritization operation is exposed following this model.
    - **DSCP**: *Differentiated Services (DiffServ) Code Point* value used to prioritize traffic of the target home device.

    # API Functionality

     This API allows to third party clients to prioritize the device connected to the user home network matching the input criteria provided. 

    # Resources and Operations overview

     The API provides a single endpoint:
    - An endpoint to set the desired DSCP prioritization status of the device matching the input criteria.
  version: 1.0.0
  termsOfService: http://swagger.io/terms/
  contact:
    name: Sample
    email: project-email@sample.com
externalDocs:
  description: Product documentation at CAMARA
  url: https://github.com/camaraproject/
servers:
  - url: https://{host}{basePath}
    variables:
      host:
        default: api.example.com
        description: Host that serves the API
      basePath:
        default: /home-devices-prioritization/v1
        description: API URL prefix for all API paths
security:
  - three_legged:
    - home-devices-prioritization-device-write
components:
  parameters:
    UserId:
      name: user_id
      description: |-
        Id of the user for which the methods apply.
        This value should be changed to the special keyword 'me' to simplify calls when access using OAuth2 with three-legged authentication
      in: path
      required: true
      schema:
        type: string
  responses:
    InvalidArgument:
      description: Problem with the client request
      headers:
        x-correlator:
          description: Correlation id for the different services
          schema:
            type: string
      content:
        application/json:
          schema:
            allOf:
              - type: object
                required:
                  - code
                properties:
                  code:
                    type: string
                    enum:
                      - INVALID_ARGUMENT
                    default: INVALID_ARGUMENT
                    description: Client specified an invalid argument, request body or query param.
              - type: object
                required:
                  - message
                properties:
                  message:
                    type: string
                    description: A human readable description of what the event represent
          examples:
            response:
              value:
                code: INVALID_ARGUMENT
                message: Client specified an invalid argument, request body or query param
    Unauthenticated:
      description: Authentication problem with the client request
      headers:
        x-correlator:
          description: Correlation id for the different services
          schema:
            type: string
      content:
        application/json:
          schema:
            allOf:
              - type: object
                required:
                  - code
                properties:
                  code:
                    type: string
                    enum:
                      - UNAUTHENTICATED
                    default: UNAUTHENTICATED
                    description: Request not authenticated due to missing, invalid, or expired credentials.
              - type: object
                required:
                  - message
                properties:
                  message:
                    type: string
                    description: A human readable description of what the event represent
          examples:
            response:
              value:
                code: UNAUTHENTICATED
                message: Request not authenticated due to missing, invalid, or expired credentials
    PermissionDenied:
      description: Client does not have sufficient permission
      headers:
        x-correlator:
          description: Correlation id for the different services
          schema:
            type: string
      content:
        application/json:
          schema:
            allOf:
              - type: object
                required:
                  - code
                properties:
                  code:
                    type: string
                    enum:
                      - PERMISSION_DENIED
                    default: PERMISSION_DENIED
                    description: Client does not have sufficient permissions to perform this action.
              - type: object
                required:
                  - message
                properties:
                  message:
                    type: string
                    description: A human readable description of what the event represent
          examples:
            response:
              value:
                code: PERMISSION_DENIED
                message: Authenticated user has no permission to access the requested resource
    NotFound:
      description: Resource Not Found
      headers:
        x-correlator:
          description: Correlation id for the different services
          schema:
            type: string
      content:
        application/json:
          schema:
            allOf:
              - type: object
                required:
                  - code
                properties:
                  code:
                    type: string
                    enum:
                      - NOT_FOUND
                    default: NOT_FOUND
                    description: The specified resource is not found
              - type: object
                required:
                  - message
                properties:
                  message:
                    type: string
                    description: A human readable description of what the event represent
          examples:
            response:
              value:
                code: NOT_FOUND
                message: A specified resource is not found
    Internal:
      description: Server error
      headers:
        x-correlator:
          description: Correlation id for the different services
          schema:
            type: string
      content:
        application/json:
          schema:
            allOf:
              - type: object
                required:
                  - code
                properties:
                  code:
                    type: string
                    enum:
                      - INTERNAL
                    default: INTERNAL
                    description: Unknown server error.Typically a server bug.
              - type: object
                required:
                  - message
                properties:
                  message:
                    type: string
                    description: A human readable description of what the event represent
          examples:
            response:
              value:
                code: INTERNAL
                message: Server error
    RouterActionsUnavailable:
      description: |-
        Service unavailable. Typically the server is down.
        In addition to regular scenario of UNAVAILABLE to handle service availability problems, another scenario may exist.
         - The router is offline ("code": "HOME_DEVICES_PRIORITIZATION.ROUTER_OFFLINE","message": "Router is not online. Try it later.").
      headers:
        x-correlator:
          description: Correlation id for the different services
          schema:
            type: string
      content:
        application/json:
          schema:
            type: object
            required:
              - code
              - message
            properties:
              code:
                type: string
                enum:
                  - UNAVAILABLE
                  - HOME_DEVICES_PRIORITIZATION.ROUTER_OFFLINE
                description: |-
                  Service unavailable. Typically the server is down.
                  Router is not online. Try it later.
              message:
                type: string
                description: A human readable description of what the event represent
          examples:
            response:
              value:
                code: UNAVAILABLE
                message: Service unavailable
    PrioritizationConflict:
      description: |-
        Device can't be prioritized. In addition to regular CONFLICT scenario to handle conflict with the current state of the target resource, another scenarios may exist:
         - HOME_DEVICES_PRIORITIZATION.TOO_MANY_DEVICES: Exceeded the maximum quantity of priority devices.
         - HOME_DEVICES_PRIORITIZATION.RSSI_BELOW_THRESHOLD: RSSI from device is below allowed threshold.
         - HOME_DEVICES_PRIORITIZATION.PRIORITY_TOO_HIGH: Prioritization requested is above the maximum permitted.
         - HOME_DEVICES_PRIORITIZATION.OCCUPANCY_ABOVE_THRESHOLD: The occupancy is above the allowed threshold.
         - HOME_DEVICES_PRIORITIZATION.DEVICE_NOT_PRIORITIZED: Device is not on priority list.
      headers:
        x-correlator:
          description: Correlation id for the different services
          schema:
            type: string
      content:
        application/json:
          schema:
            type: object
            required:
              - code
              - message
            properties:
              code:
                type: string
                enum:
                  - HOME_DEVICES_PRIORITIZATION.TOO_MANY_DEVICES
                  - HOME_DEVICES_PRIORITIZATION.RSSI_BELOW_THRESHOLD
                  - HOME_DEVICES_PRIORITIZATION.PRIORITY_TOO_HIGH
                  - HOME_DEVICES_PRIORITIZATION.OCCUPANCY_ABOVE_THRESHOLD
                  - HOME_DEVICES_PRIORITIZATION.DEVICE_NOT_PRIORITIZED
                description: Device can't be prioritized because a precondition does not hold
              message:
                type: string
                description: A human readable description of what the event represent
          examples:
            response:
              value:
                code: HOME_DEVICES_PRIORITIZATION.TOO_MANY_DEVICES
                message: Exceeded the maximum quantity of priority devices
    Timeout:
      description: Request time exceeded. If it happens repeatedly, consider reducing the request complexity
      headers:
        x-correlator:
          description: Correlation id for the different services
          schema:
            type: string
      content:
        application/json:
          schema:
            allOf:
              - type: object
                required:
                  - code
                properties:
                  code:
                    type: string
                    enum:
                      - TIMEOUT
                    default: TIMEOUT
                    description: Request timeout exceeded
              - type: object
                required:
                  - message
                properties:
                  message:
                    type: string
                    description: A human readable description of what the event represent
          examples:
            response:
              value:
                code: TIMEOUT
                message: Request timeout exceeded. If it happens repeatedly, consider reducing the request complexity
    NoDeviceMatch:
      description: |-
        Resource Not Found.
        In addition to regular scenario of NOT_FOUND, another scenario may exist.
         - There is no device matching the input criteria. ("code": "HOME_DEVICES_PRIORITIZATION.NO_DEVICE_MATCH","message": "No connected device found for the IP addresses provided.").
      headers:
        x-correlator:
          description: Correlation id for the different services
          schema:
            type: string
      content:
        application/json:
          schema:
            type: object
            required:
              - code
              - message
            properties:
              code:
                type: string
                enum:
                  - HOME_DEVICES_PRIORITIZATION.NO_DEVICE_MATCH
                description: There is no device matching the input criteria
              message:
                type: string
                description: A human readable description of what the event represent
          examples:
            response:
              value:
                code: HOME_DEVICES_PRIORITIZATION.NO_DEVICE_MATCH
                message: No connected device found for the IP address provided
  securitySchemes:
    three_legged:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://auth.example.com/authorize
          tokenUrl: https://auth.example.com/token
          scopes:
            home-devices-prioritization-device-write: Write Home Devices Prioritization
  schemas:
    DevicePrioritizationUpdate:
      type: object
      description: Payload to change the prioritization status of a device.
      required:
        - dscp
        - ip_address
        - public_ip_address
      properties:
        dscp:
          type: string
          description: DSCP information for QoS
          enum:
            - CS0
            - CS1
            - AF11
            - AF12
            - AF13
            - CS2
            - AF21
            - AF22
            - AF23
            - CS3
            - AF31
            - AF32
            - AF33
            - CS4
            - AF41
            - AF42
            - AF43
            - CS5
            - EF
            - CS6
            - CS7
            - MAX_ALLOWED
          example: CS0
        ip_address:
          type: string
          description: Internal IP address of the connected device in the LAN.
          example: 192.168.1.27
        public_ip_address:
          type: string
          description: Public IP address of the device.
          example: 83.58.37.57
